const slots = [
  {
    id: 1,
    zone: 1,
    name: "Z1LP1",
    slotType: "LP",
    ep1Distance: 1,
    ep2Distance: 4,
    ep3Distance: 8,
  },
  {
    id: 2,
    zone: 1,
    name: "Z1LP2",
    slotType: "LP",
    ep1Distance: 2,
    ep2Distance: 5,
    ep3Distance: 7,
  },
  {
    id: 3,
    zone: 1,
    name: "Z1LP3",
    slotType: "LP",
    ep1Distance: 3,
    ep2Distance: 6,
    ep3Distance: 6,
  },
  {
    id: 4,
    zone: 1,
    name: "Z1LP4",
    slotType: "LP",
    ep1Distance: 4,
    ep2Distance: 7,
    ep3Distance: 5,
  },
  {
    id: 5,
    zone: 1,
    name: "Z1LP5",
    slotType: "LP",
    ep1Distance: 5,
    ep2Distance: 8,
    ep3Distance: 4,
  },

  {
    id: 6,
    zone: 2,
    name: "Z2SP1",
    slotType: "SP",
    ep1Distance: 2,
    ep2Distance: 3,
    ep3Distance: 8,
  },
  {
    id: 7,
    zone: 2,
    name: "Z2SP2",
    slotType: "SP",
    ep1Distance: 3,
    ep2Distance: 4,
    ep3Distance: 7,
  },
  {
    id: 8,
    zone: 2,
    name: "Z2SP3",
    slotType: "SP",
    ep1Distance: 4,
    ep2Distance: 5,
    ep3Distance: 6,
  },
  {
    id: 9,
    zone: 2,
    name: "Z2SP4",
    slotType: "SP",
    ep1Distance: 5,
    ep2Distance: 6,
    ep3Distance: 5,
  },
  {
    id: 10,
    zone: 2,
    name: "Z2SP5",
    slotType: "SP",
    ep1Distance: 6,
    ep2Distance: 7,
    ep3Distance: 4,
  },
  {
    id: 11,
    zone: 3,
    name: "Z3SP1",
    slotType: "SP",
    ep1Distance: 4,
    ep2Distance: 1,
    ep3Distance: 5,
  },
  {
    id: 12,
    zone: 3,
    name: "Z3SP2",
    slotType: "SP",
    ep1Distance: 5,
    ep2Distance: 2,
    ep3Distance: 4,
  },
  {
    id: 13,
    zone: 3,
    name: "Z3SP3",
    slotType: "SP",
    ep1Distance: 6,
    ep2Distance: 3,
    ep3Distance: 3,
  },
  {
    id: 14,
    zone: 3,
    name: "Z3SP4",
    slotType: "SP",
    ep1Distance: 7,
    ep2Distance: 4,
    ep3Distance: 2,
  },
  {
    id: 15,
    zone: 3,
    name: "Z3SP5",
    slotType: "SP",
    ep1Distance: 8,
    ep2Distance: 5,
    ep3Distance: 1,
  },

  {
    id: 16,
    zone: 4,
    name: "Z4MP1",
    slotType: "MP",
    ep1Distance: 6,
    ep2Distance: 1,
    ep3Distance: 5,
  },
  {
    id: 17,
    zone: 4,
    name: "Z4MP2",
    slotType: "MP",
    ep1Distance: 7,
    ep2Distance: 2,
    ep3Distance: 6,
  },
  {
    id: 18,
    zone: 4,
    name: "Z4MP3",
    slotType: "MP",
    ep1Distance: 8,
    ep2Distance: 3,
    ep3Distance: 7,
  },
  {
    id: 19,
    zone: 4,
    name: "Z4MP4",
    slotType: "MP",
    ep1Distance: 9,
    ep2Distance: 4,
    ep3Distance: 8,
  },
  {
    id: 20,
    zone: 4,
    name: "Z4MP5",
    slotType: "MP",
    ep1Distance: 10,
    ep2Distance: 5,
    ep3Distance: 9,
  },
  {
    id: 21,
    zone: 5,
    name: "Z5MP1",
    slotType: "MP",
    ep1Distance: 7,
    ep2Distance: 4,
    ep3Distance: 3,
  },
  {
    id: 21,
    zone: 5,
    name: "Z5MP2",
    slotType: "MP",
    ep1Distance: 8,
    ep2Distance: 5,
    ep3Distance: 4,
  },
  {
    id: 23,
    zone: 5,
    name: "Z5MP3",
    slotType: "MP",
    ep1Distance: 9,
    ep2Distance: 6,
    ep3Distance: 5,
  },
  {
    id: 24,
    zone: 5,
    name: "Z5MP4",
    slotType: "MP",
    ep1Distance: 10,
    ep2Distance: 7,
    ep3Distance: 6,
  },
  {
    id: 25,
    zone: 5,
    name: "Z5MP5",
    slotType: "MP",
    ep1Distance: 11,
    ep2Distance: 8,
    ep3Distance: 7,
  },

  {
    id: 26,
    zone: 6,
    name: "Z6LP1",
    slotType: "LP",
    ep1Distance: 11,
    ep2Distance: 6,
    ep3Distance: 1,
  },
  {
    id: 27,
    zone: 6,
    name: "Z6LP2",
    slotType: "LP",
    ep1Distance: 12,
    ep2Distance: 7,
    ep3Distance: 2,
  },
  {
    id: 28,
    zone: 6,
    name: "Z6LP3",
    slotType: "LP",
    ep1Distance: 13,
    ep2Distance: 8,
    ep3Distance: 3,
  },
  {
    id: 29,
    zone: 6,
    name: "Z6LP4",
    slotType: "LP",
    ep1Distance: 14,
    ep2Distance: 9,
    ep3Distance: 4,
  },
  {
    id: 30,
    zone: 6,
    name: "Z6LP5",
    slotType: "LP",
    ep1Distance: 15,
    ep2Distance: 10,
    ep3Distance: 5,
  },
];

module.exports = { slots };
